base_timezone: America/New_York

firewall_allow_ssh: true
firewall_allow_wireguard: true
firewall_wireguard_interface: wg0
firewall_wireguard_port: 51820
firewall_limit_ssh_src: false
firewall_local_dns: true
firewall_crossfire_server: false

wireguard_basedir: "/etc/wireguard"
wireguard_server_conf: wg0.conf
wireguard_wireguard_interface: "{{ firewall_wireguard_interface }}"
wireguard_endpoint: "{{ ansible_default_ipv4.address }}"
wireguard_listen_port: 51820
wireguard_keepalive: false
wireguard_keepalive_sec: 25
wireguard_clients:
  - phone
  - laptop
wireguard_subnet: "10.11.0"
wireguard_dns: "{{ wireguard_subnet }}.1"

unbound_dns_interface: "{{ wireguard_dns }}"
unbound_log_queries: false
unbound_log_verbosity: 1
