---
# tasks file for roles/unbound
- name: Install unbound
  community.general.openbsd_pkg:
    name: libunbound
    state: present

- name: Configure rc.local unbound
  ansible.builtin.lineinfile:
    path: /etc/rc.local
    line: "rcctl -f start unbound"

- name: Copy unbound conf
  ansible.builtin.template:
    src: templates/unbound.conf.j2
    dest: /var/unbound/etc/unbound.conf
    owner: root
    group: wheel
    mode: "0600"

- name: Enable logging
  when: unbound_log_queries
  block:
  - name: Create log dirs
    ansible.builtin.file:
      path: /var/unbound/var/log
      state: directory
      recurse: true
      owner: root
      group: _unbound
      mode: "0770"

  - name: Check for log file
    ansible.builtin.stat:
      path: /var/unbound/var/log/unbound.log
    register: unbound_log

  - name: Create log file
    ansible.builtin.file:
      path: /var/unbound/var/log/unbound.log
      state: touch
      owner: root
      group: _unbound
      mode: "0770"
    when: not unbound_log.stat.exists

- name: Start unbound
  ansible.builtin.command:
    cmd: rcctl -f start unbound
  changed_when: false
  failed_when: false
