---
# handlers file for roles/base
- name: Reboot Server
  ansible.builtin.reboot:

- name: Restart sshd
  ansible.builtin.command:
    cmd: rcctl restart sshd
  changed_when: false

- name: Restart snmpd
  ansible.builtin.command:
    cmd: rcctl restart snmpd
  changed_when: false
