---
# defaults file for roles/firewall
firewall_allow_ssh: true
firewall_allow_snmpd: true
firewall_allow_wireguard: true
firewall_wireguard_interface: wg0
firewall_wireguard_port: 51820
firewall_limit_ssh_src: false
firewall_local_dns: true
firewall_crossfire_server: false
