---
# tasks file for roles/firewall
- name: Add rules for pf
  ansible.builtin.template:
    src: templates/pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0600

- name: Configure rc.conf.local pf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf.local
    regexp: "^pf=NO"
    line: "pf=YES"

- name: Configure rc.conf.local pflogd
  ansible.builtin.lineinfile:
    path: /etc/rc.conf.local
    regexp: "^pflogd.*NO$"
    line: "pflogd_flags=YES"

- name: Start and enable pf
  ansible.builtin.shell:
    cmd: pfctl -e && pfctl -f /etc/pf.conf
  changed_when: false
  failed_when: false

- name: Start pflogd
  ansible.builtin.command:
    cmd: rcctl start pflogd
  changed_when: false
  failed_when: false
