---
# tasks file for roles/firewall
- name: Limit ssh src addrs
  block:
  - name: Check ssh ssh_allow table
    ansible.builtin.assert:
      that:
        - firewall_ssh_srcs is defined

  - name: Rc.local ssh src table update
    ansible.builtin.lineinfile:
      path: /etc/rc.local
      line: "pfctl -t ssh_src -Tr {{ item }}"
    with_items: "{{ firewall_ssh_srcs }}"

  - name: Cron ssh src table update
    ansible.builtin.lineinfile:
      path: /var/cron/tabs/root
      line: "*/5 * * * * pfctl -t ssh_src -Tr {{ item }} > /dev/null 2>&1"
    with_items: "{{ firewall_ssh_srcs }}"
  when: firewall_limit_ssh_src

- name: Add rules for pf
  ansible.builtin.template:
    src: templates/pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: 0600

- name: Update ssh src table
  ansible.builtin.command:
    cmd: pfctl -t ssh_src -Tr {{ item }}
  with_items: "{{ firewall_ssh_srcs }}"
  when: firewall_limit_ssh_src
  changed_when: false
  ignore_errors: true

- name: Check for rc.conf.local
  ansible.builtin.stat:
    path: /etc/rc.conf.local
  register: rc_conf_local

- name: Create rc.conf.local
  ansible.builtin.file:
    path: /etc/rc.conf.local
    state: touch
    owner: root
    group: wheel
    mode: 0600
  when: not rc_conf_local.stat.exists

- name: Configure rc.conf.local pf
  ansible.builtin.lineinfile:
    path: /etc/rc.conf.local
    regexp: "^pf=NO"
    line: "pf=YES"

- name: Configure rc.conf.local pflogd
  ansible.builtin.lineinfile:
    path: /etc/rc.conf.local
    regexp: "^pflogd.*NO$"
    line: "pflogd_flags=YES"

- name: Start and enable pf
  ansible.builtin.shell:
    cmd: pfctl -e && pfctl -f /etc/pf.conf
  changed_when: false
  failed_when: false

- name: Start pflogd
  ansible.builtin.command:
    cmd: rcctl start pflogd
  changed_when: false
  failed_when: false
