- name: Start/enable cron
  ansible.builtin.shell:
    cmd: rcctl enable cron && rcctl start cron
  changed_when: false
  failed_when: false

- name: Add daily.local
  ansible.builtin.copy:
    src: files/daily.local
    dest: /etc/daily.local
    owner: root
    group: wheel
    mode: 0600
