---
# tasks file for roles/base
- name: Update system
  ansible.builtin.import_tasks: update.yml
  tags: base_update

- name: Configure sshd
  ansible.builtin.copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: wheel
    mode: "0644"
  notify: Restart sshd
  tags: base_sshd

- name: Set timezone
  ansible.builtin.file:
    src: "/usr/share/zoneinfo/{{ base_timezone }}"
    dest: /etc/localtime
    state: link
    force: true
    owner: root
    group: wheel
  tags: base_timezone

- name: Check for rc.local
  ansible.builtin.stat:
    path: /etc/rc.local
  register: rc_local

- name: Create rc.local
  ansible.builtin.file:
    path: /etc/rc.local
    state: touch
    owner: root
    group: wheel
    mode: "0644"
  when: not rc_local.stat.exists

- name: Install packages
  ansible.builtin.import_tasks: packages.yml
  tags: base_packages

- name: Set root shell
  ansible.builtin.import_tasks: shell.yml
  tags: base_shell

- name: Configure cron
  ansible.builtin.import_tasks: cron.yml
  tags: base_cron

- name: Configure aide
  ansible.builtin.import_tasks: aide.yml
  tags: base_aide

- name: Configure snmpd
  ansible.builtin.import_tasks: snmpd.yml
  when: base_snmpd
  tags: base_snmpd
