---
- name: Install packages
  community.general.openbsd_pkg:
    name: "{{ item }}"
  with_items: "{{ openbsd_init_package_install }}"

- name: Create gnuwatch symlink
  ansible.builtin.file:
    src: /usr/local/bin/gnuwatch
    dest: /usr/local/bin/watch
    state: link
    owner: root
    group: wheel
    mode: 0755

- name: Create updatedb symlink
  ansible.builtin.file:
    src: /usr/libexec/locate.updatedb
    dest: /usr/local/bin/updatedb
    state: link
    owner: root
    group: wheel
    mode: 0755
