- hosts: all
  remote_user: root
  vars_files:
    - ../group_vars/main.yml
  roles:
    - role: roles/base
      tags: base_role
    - role: roles/firewall
      vars:
        home_ddns: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  38643563396432386433333633323434333839393737386235326661313034643765653339383434
                  6433323936393537643034613264326663656231636439330a333432633738336339396663643964
                  63333731616535613261303536313965386439313731636530333364376532326435613363336337
                  3235383138363634390a343337663265363237633031653432333930306134623738643531376166
                  64333333336366663037386232313339373935346433353439666165623030386165
        firewall_limit_ssh_src: true
        firewall_ssh_srcs:
          - "{{ home_ddns }}"
      tags: firewall_role
    - role: roles/wireguard
      vars:
        wireguard_clients:
          - phone
          - laptop
          - client1
          - client2
          - client3
      tags: wireguard_role
    - role: roles/unbound
      vars:
        unbound_log_queries: false
        unbound_ad_lists:
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/extra.txt
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
          - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/update.txt
          - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt
          - https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
        unbound_passlist: true
        unbound_blocklist: true
        unbound_blocklist_loc: "../../custom/blocklist.txt"
        unbound_passlist_loc: "../../custom/passlist.txt"
      tags: unbound_role
