- hosts: all
  become: true
  vars_files:
    - ../group_vars/main.yml
  roles:
    - role: roles/base
      tags: base_role
    - role: roles/firewall
      tags: firewall_role
    - role: roles/wireguard
      tags: wireguard_role
    - role: roles/unbound
      tags: unbound_role
