- hosts: unbound
  become: true
  roles:
    - role: roles/base
      tags: base_role
    - role: roles/firewall
      vars:
        - firewall_allow_wireguard: false
      tags: firewall_role
    - role: roles/unbound
      tags: unbound_role
