- name: Enable ipv4 fwd
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    line: "{{ item }}"
  loop:
    - net.inet.ip.forwarding=1
    - net.inet6.ip6.forwarding=1
  notify: Reboot Server

- name: Create wg0 iface
  ansible.builtin.template:
    src: templates/hostname.wg.j2
    dest: "/etc/hostname.{{ wireguard_wireguard_interface }}"
    owner: root
    group: wheel
    mode: 0640
  notify: Reboot Server
